package Server;
import Shared.SessionData;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.ConcurrentHashMap;

public class SessionManager {

    // ── The map — token string → full session snapshot ───────────
    // ConcurrentHashMap: thread-safe, no external synchronization needed
    // for individual get/put/remove operations.
    private final ConcurrentHashMap<String, SessionData> sessions =
            new ConcurrentHashMap<>();

    // ────────────────────────────────────────────────────────────
    //  Write operations
    // ────────────────────────────────────────────────────────────

    /**
     * Stores a new session in the map.
     * Called by AuthHandler immediately after a successful LOGIN.
     *
     * If a session with the same token already exists (astronomically
     * unlikely with UUID v4 but theoretically possible), the existing
     * session is silently replaced. In practice this is a non-issue —
     * UUID v4 has 2^122 possible values.
     *
     * @param token  the UUID token generated by AuthHandler
     * @param data   the full session snapshot including userId, role, IP, UDP port
     */
    public void addSession(String token, SessionData data) {
        if (token == null || token.isBlank() || data == null) {
            throw new IllegalArgumentException(
                    "SessionManager.addSession: token and data must not be null");
        }
        sessions.put(token, data);
        System.out.println("[SessionManager] Session added — " + data
                + "  | Active sessions: " + sessions.size());
    }

    /**
     * Removes a session from the map.
     * Called by ClientHandler's finally block when a client disconnects,
     * and by AuthHandler when it processes a LOGOUT command.
     *
     * Passing a null or unknown token is safe — it is a no-op.
     * There is never a reason to throw on removeSession() because by
     * the time it is called the session may already be gone (e.g. the
     * client sent LOGOUT and then immediately closed the connection,
     * causing both the LOGOUT handler and the finally block to call
     * removeSession() for the same token).
     *
     * @param token  the session token to invalidate
     */
    public void removeSession(String token) {
        if (token == null || token.isBlank()) return;

        SessionData removed = sessions.remove(token);
        if (removed != null) {
            System.out.println("[SessionManager] Session removed — "
                    + removed.getUsername()
                    + " (alive " + removed.getAgeSeconds() + "s)"
                    + "  | Active sessions: " + sessions.size());
        }
    }

    // ────────────────────────────────────────────────────────────
    //  Read operations
    // ────────────────────────────────────────────────────────────

    /**
     * Returns the SessionData for a given token, or null if the token
     * is unknown or expired (i.e. has been removed by removeSession()).
     *
     * This is the primary method called by every handler that needs to
     * validate authentication. The pattern across all handlers is:
     *
     *   SessionData session = sessionManager.getSession(params[0]);
     *   if (session == null) return ResponseBuilder.error("Not logged in");
     *   // proceed — session is valid
     *
     * @param token  the session token from the command params
     * @return       the SessionData or null if the session does not exist
     */
    public SessionData getSession(String token) {
        if (token == null || token.isBlank()) return null;
        return sessions.get(token);
    }

    /**
     * Returns the userId for a given token without exposing the full
     * SessionData object. Convenience method for handlers that only
     * need the userId and want to avoid a null-check on SessionData.
     *
     * Returns -1 if the token is unknown — callers should treat -1
     * as "not logged in" and return an error response.
     *
     * @param token  the session token
     * @return       the userId, or -1 if the session does not exist
     */
    public int getUserId(String token) {
        SessionData session = getSession(token);
        return session != null ? session.getUserId() : -1;
    }

    /**
     * Returns the role for a given token.
     * Returns null if the session does not exist.
     *
     * @param token  the session token
     * @return       "USER", "ADMIN", or null
     */
    public String getRole(String token) {
        SessionData session = getSession(token);
        return session != null ? session.getRole() : null;
    }

    /**
     * Returns the client IP address stored at login time.
     * Used by UDPBroadcaster when addressing a notification packet.
     *
     * Returns null if the session does not exist.
     *
     * @param token  the session token
     * @return       IP address string, or null
     */
    public String getClientIP(String token) {
        SessionData session = getSession(token);
        return session != null ? session.getClientIP() : null;
    }

    /**
     * Returns the UDP port the client registered at login time.
     * Used by UDPBroadcaster alongside getClientIP().
     *
     * Returns -1 if the session does not exist.
     *
     * @param token  the session token
     * @return       UDP port number, or -1
     */
    public int getClientUdpPort(String token) {
        SessionData session = getSession(token);
        return session != null ? session.getClientUdpPort() : -1;
    }

    /**
     * Returns true if the token belongs to an active ADMIN session.
     * Equivalent to calling getSession(token).isAdmin() with a null guard.
     * Used by AdminHandler.requireAdmin() as a one-liner check.
     *
     * @param token  the session token
     * @return       true only if the session exists AND role is ADMIN
     */
    public boolean isAdmin(String token) {
        SessionData session = getSession(token);
        return session != null && session.isAdmin();
    }

    // ────────────────────────────────────────────────────────────
    //  Diagnostics
    // ────────────────────────────────────────────────────────────

    /**
     * Returns the number of currently active sessions.
     * Used by Server for startup logging and health checks.
     * The count is a snapshot — it may change immediately after this
     * call returns, so do not use it for logic decisions.
     */
    public int getActiveSessionCount() {
        return sessions.size();
    }

    /**
     * Returns an unmodifiable snapshot of all active sessions.
     * Intended for admin diagnostics or a future "active users" feature.
     *
     * This is a point-in-time snapshot — sessions may be added or removed
     * after this list is returned. Safe to iterate without synchronization
     * because it is a separate copy.
     *
     * @return  unmodifiable list of all current SessionData objects
     */
    public List<SessionData> getAllSessions() {
        return Collections.unmodifiableList(
                new ArrayList<>(sessions.values()));
    }

    /**
     * Removes all sessions from the map.
     * Called by Server.shutdown() to cleanly invalidate all sessions
     * before the server process exits.
     */
    public void clearAll() {
        int count = sessions.size();
        sessions.clear();
        System.out.println("[SessionManager] All sessions cleared ("
                + count + " removed).");
    }
}
