package Shared;

public enum Command {
    REGISTER,
    LOGIN,
    LOGOUT,
    GET_PRODUCTS,
    GET_PRODUCT,
    GET_CATEGORIES,
    CART_ADD,
    CART_REMOVE,
    CART_VIEW,
    CART_CLEAR,
    CHECKOUT,
    ORDER_HISTORY,
    ADMIN_ADD_PRODUCT,
    ADMIN_EDIT_PRODUCT,
    ADMIN_DELETE_PRODUCT,
    ADMIN_LIST_ORDERS,
    ADMIN_UPDATE_STATUS,
    ADMIN_LIST_USERS
}
